export const result = [
  {
    id: 999991,
    url: 'https://yts.lt/movies/pope-francis-a-man-of-his-word-2018',
    title: 'some-title-1',
    year: 9991,
    rating: 8.5,
    runtime: 191,
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Sci-Fi', 'dummy-odd'],
    summary: 'some-summary',
    description_full: 'some-description',
    small_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/small-cover.jpg',
    medium_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/medium-cover.jpg',
    large_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/large-cover.jpg',
  },
  {
    id: 999992,
    url: 'https://yts.lt/movies/pope-francis-a-man-of-his-word-2018',
    title: 'some-title-2',
    year: 9999,
    rating: 8.5,
    runtime: 192,
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Sci-Fi', 'dummy-even'],
    summary: 'some-summary',
    description_full: 'some-description',
    small_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/small-cover.jpg',
    medium_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/medium-cover.jpg',
    large_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/large-cover.jpg',
  },
  {
    id: 999993,
    url: 'https://yts.lt/movies/pope-francis-a-man-of-his-word-2018',
    title: 'some-title-3',
    year: 9993,
    rating: 8.5,
    runtime: 193,
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Sci-Fi', 'dummy-odd'],
    summary: 'some-summary',
    description_full: 'some-description',
    small_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/small-cover.jpg',
    medium_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/medium-cover.jpg',
    large_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/large-cover.jpg',
  },
  {
    id: 999994,
    url: 'https://yts.lt/movies/pope-francis-a-man-of-his-word-2018',
    title: 'some-title-4',
    year: 9994,
    rating: 8.5,
    runtime: 194,
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Sci-Fi', 'dummy-even'],
    summary: 'some-summary',
    description_full: 'some-description',
    small_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/small-cover.jpg',
    medium_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/medium-cover.jpg',
    large_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/large-cover.jpg',
  },
  {
    id: 999995,
    url: 'https://yts.lt/movies/pope-francis-a-man-of-his-word-2018',
    title: 'some-title-5',
    year: 9995,
    rating: 8.5,
    runtime: 195,
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Sci-Fi', 'dummy-odd'],
    summary: 'some-summary',
    description_full: 'some-description',
    small_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/small-cover.jpg',
    medium_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/medium-cover.jpg',
    large_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/large-cover.jpg',
  },
  {
    id: 999996,
    url: 'https://yts.lt/movies/pope-francis-a-man-of-his-word-2018',
    title: 'some-title-6',
    year: 9996,
    rating: 8.5,
    runtime: 196,
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Sci-Fi', 'dummy-even'],
    summary: 'some-summary',
    description_full: 'some-description',
    small_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/small-cover.jpg',
    medium_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/medium-cover.jpg',
    large_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/large-cover.jpg',
  },
  {
    id: 999997,
    url: 'https://yts.lt/movies/pope-francis-a-man-of-his-word-2018',
    title: 'some-title-7',
    year: 9997,
    rating: 8.5,
    runtime: 197,
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Sci-Fi', 'dummy-odd'],
    summary: 'some-summary',
    description_full: 'some-description',
    small_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/small-cover.jpg',
    medium_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/medium-cover.jpg',
    large_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/large-cover.jpg',
  },
  {
    id: 999998,
    url: 'https://yts.lt/movies/pope-francis-a-man-of-his-word-2018',
    title: 'some-title-8',
    year: 9998,
    rating: 8.5,
    runtime: 198,
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Sci-Fi', 'dummy-even'],
    summary: 'some-summary',
    description_full: 'some-description',
    small_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/small-cover.jpg',
    medium_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/medium-cover.jpg',
    large_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/large-cover.jpg',
  },
  {
    id: 999999,
    url: 'https://yts.lt/movies/pope-francis-a-man-of-his-word-2018',
    title: 'some-title-9',
    year: 9999,
    rating: 8.5,
    runtime: 199,
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Sci-Fi', 'dummy-odd'],
    summary: 'some-summary',
    description_full: 'some-description',
    small_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/small-cover.jpg',
    medium_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/medium-cover.jpg',
    large_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/large-cover.jpg',
  },
  {
    id: 999990,
    url: 'https://yts.lt/movies/pope-francis-a-man-of-his-word-2018',
    title: 'some-title-0',
    year: 9990,
    rating: 8.5,
    runtime: 190,
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Sci-Fi', 'dummy-even'],
    summary: 'some-summary',
    description_full: 'some-description',
    small_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/small-cover.jpg',
    medium_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/medium-cover.jpg',
    large_cover_image: 'https://yts.lt/assets/images/movies/pope_francis_a_man_of_his_word_2018/large-cover.jpg',
  },
];
